In [9]:
import numpy as np

a = np.array([[13, -4, 1], [-4, 13, -4], [1, -4, 13]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

reconstructed_matrix = np.dot(np.dot(np.linalg.inv(eigenvectors), np.diag(eigenvalues)), eigenvectors.T)

relative_error = np.linalg.norm(a - reconstructed_matrix) / np.linalg.norm(a)

print("Точность", relative_error)

Собственные значения:
[19.17890835 12.          7.82109165]

Собственные векторы:
[[-5.21546999e-01  7.07106781e-01  4.77481651e-01]
 [ 6.75261027e-01 -3.48687529e-16  7.37578840e-01]
 [-5.21546999e-01 -7.07106781e-01  4.77481651e-01]]
Точность 1.2228900810009267
